Simple changes on the road to multiarch support (hello ARM64)
KatharaFramework/Kathara pull request #130
Opened 2021-07-17 20:45 UTC by nopid

**- What I did**
On the road to add Apple M1 ARM64 support both under Debian based OS and macOS (first contribution to fix #104). With small changes I managed to build and run ARM64 Kathará images on Ubuntu 20 with a proper `.deb` generated with the Linux-Deb script. Under macOS, the proof of concept works, one can run kathará through python directly (unfortunately pyinstaller is not properly working yet). 

My system is a Macbook Pro M1 laptop running macOS 11.4. Ubuntu 20 is running natively inside an UTM virtual machine.

Notice that this is only part of the solution, all the Kathará docker images have to be rebuilt for ARM64, including the `NetworkPlugin` image. I plan to open issues in the proper repositories.

**- How I did it**
1) change Architecture in the control file from `amd64` to `any` so that it built an ARM64 `.deb` from Ubuntu with `make docker-unsigned`
2) moved `PLUGIN_NAME` from a constant inside https://github.com/KatharaFramework/Kathara/blob/b4b44d3f1af3130cf9212fbdc4e1548ec94ab1da/src/Resources/manager/docker/DockerPlugin.py#L8 into a `plugin_name` setting in the `kathara.conf` file to permit a selection per architecture.

**- How to verify it**
Under ARM64 Ubuntu 20:
1) use `make docker-unsigned` inside `scripts/Linux-Deb/` to compile and then install `scripts/Linux-Deb/Output/kathara_3.1.0-1focal_amd64.deb` with `dpkg`
2) modify your `kathara.conf` file to have `plugin_name` and `image` point to ARM64 images, for example:
```
 "plugin_name": "nopid/katharanp:latest",
 "image": "nopid/quagga:debian10",
```
3) Enjoy Kathará! (tested with 2 vstart machines on a same hub and with some labs from `Kathara-Labs`)

**- Description for the changelog**

better multiarch support: build deb to any architecture, add plugin_name to settings

2021-07-18 21:29 UTC, nopid commented
After https://github.com/KatharaFramework/NetworkPlugin/pull/3 is resolved, I plan to submit a second PR to change default `plugin_name` setting value from `kathara/katharanp:latest` to `'kathara/katharanp:amd64` or `'kathara/katharanp:arm64` depending on `platform.machine()`. This would ensure upon installation that kathará is configured to use the proper plugin out of the box.

2021-10-11 11:18 UTC, Skazza94 commented
Hi @nopid,
finally we're addressing the M1/ARM compatibility. 

Unfortunately, last week we released a new version of Kathará which has a lot of changes in the code. So, this pull request is now conflicting. Can you pull the new master and apply your changes?

I'll add some comments to your code, to suggest some enhancements.

Thanks.

2021-10-11 11:22 UTC, Skazza94 requested changes

2021-10-11 11:22 UTC, Skazza94 commented on scripts/Linux-Deb/debian/control
> +Architecture: any
Doing the multiarch compilation on Debian is a little bit tricky, we'll address it in future. Please remove this change.

2021-10-11 11:22 UTC, Skazza94 commented on src/Resources/manager/docker/DockerPlugin.py
> -PLUGIN_NAME = "kathara/katharanp:latest"
Do not put the plugin_name into Settings. 
Define `PLUGIN_NAME` as `PLUGIN_NAME = 'kathara/katharanp:' + utils.arch()`.

This will automatically make it compatible, we'll push the ARM64 plugin soon.

2021-10-11 11:22 UTC, Skazza94 commented on src/Resources/setting/Setting.py
> +    "plugin_name": 'kathara/katharanp:' + utils.arch(),
See the comment above.

2021-10-13 12:04 UTC, closed without merging

2021-10-13 16:16 UTC, nopid commented
This PR was auto-closed by github, the new one taking @Skazza94 comments into account is https://github.com/KatharaFramework/Kathara/pull/139